### PR TITLE
[Matrix] API related update, cleanup, license add, german language add

### PR DESCRIPTION
**Pull request by AlwinEsch**
Changes related to https://github.com/xbmc/xbmc/pull/18251

There about addon no code changes needed only reworked in his background "C" parts.

Also some other changes included.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
@sarbes are this changes here OK for you?

Have itself no rights to this repo and is by you :smile:

**Comment by AlwinEsch** [comment]
Note: The request on Kodi is in and this need merge if OK

**Comment by AlwinEsch** [comment]
@sarbes how is the state of this addon?

With API differences is previous Version no more usable in Kodi.

**Comment by sarbes** [comment]
Sorry, I have not seen this before. I'll look at it on the weekend.

As for the German translation, I have my own version which I prefer. I'm about to finalize some new features which need new strings. I'm sorry you put work into it :/.

Next time, feel free to ping me directly on Slack.

**Comment by AlwinEsch** [comment]
As https://github.com/xbmc/xbmc/pull/18408 now in this can also in.

**Comment by sarbes** [comment]
Sorry for the long delay.

**Pull request merged**
